// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\repository\repository.go
// Generated by this command: mockgen --source=.\internal\repository\repository.go  --destination=.\internal\repository\mocks\mock_repository.go --package=mocks

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	repository "go-url-shortener/internal/repository"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockURLRepositoryInterface is a mock of URLRepositoryInterface interface.
type MockURLRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockURLRepositoryInterfaceMockRecorder
}

// MockURLRepositoryInterfaceMockRecorder is the mock recorder for MockURLRepositoryInterface.
type MockURLRepositoryInterfaceMockRecorder struct {
	mock *MockURLRepositoryInterface
}

// NewMockURLRepositoryInterface creates a new mock instance.
func NewMockURLRepositoryInterface(ctrl *gomock.Controller) *MockURLRepositoryInterface {
	mock := &MockURLRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockURLRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLRepositoryInterface) EXPECT() *MockURLRepositoryInterfaceMockRecorder {
	return m.recorder
}

// BatchSave mocks base method.
func (m *MockURLRepositoryInterface) BatchSave(ctx context.Context, items []repository.BatchEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchSave", ctx, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchSave indicates an expected call of BatchSave.
func (mr *MockURLRepositoryInterfaceMockRecorder) BatchSave(ctx, items interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchSave", reflect.TypeOf((*MockURLRepositoryInterface)(nil).BatchSave), ctx, items)
}

// Get mocks base method.
func (m *MockURLRepositoryInterface) Get(shortID string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", shortID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockURLRepositoryInterfaceMockRecorder) Get(shortID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockURLRepositoryInterface)(nil).Get), shortID)
}

// Ping mocks base method.
func (m *MockURLRepositoryInterface) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockURLRepositoryInterfaceMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockURLRepositoryInterface)(nil).Ping), ctx)
}

// Save mocks base method.
func (m *MockURLRepositoryInterface) Save(shortID, originalURL string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Save", shortID, originalURL)
}

// Save indicates an expected call of Save.
func (mr *MockURLRepositoryInterfaceMockRecorder) Save(shortID, originalURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockURLRepositoryInterface)(nil).Save), shortID, originalURL)
}
