// Code generated by generate:reset; DO NOT EDIT.

package repository

func (urle *URLEntry) Reset() {
	if urle == nil {
		return
	}
	urle.ShortID = ""
	urle.OriginalURL = ""
	urle.UserID = ""
	urle.DeletedFlag = false
}

func (urlr *URLRepository) Reset() {
	if urlr == nil {
		return
	}
	clear(urlr.store)
	clear(urlr.rev)
	clear(urlr.userIndex)
}
