// Code generated by generate:reset; DO NOT EDIT.

package resetexample

func (rss *ResetableSimpleStruct) Reset() {
	if rss == nil {
		return
	}
	rss.Counter = 0
	rss.Name = ""
}

func (rs *ResetableStruct) Reset() {
	if rs == nil {
		return
	}
	rs.IntField = 0
	rs.Int8Field = 0
	rs.Int64Field = 0
	rs.UintField = 0
	rs.FloatField = 0
	rs.StringField = ""
	rs.BoolField = false
	rs.SliceField = rs.SliceField[:0]
	clear(rs.MapField)
	if rs.IntPtr != nil {
		*rs.IntPtr = 0
	}
	if rs.StrPtr != nil {
		*rs.StrPtr = ""
	}
	if rs.BoolPtr != nil {
		*rs.BoolPtr = false
	}
	if rs.Child != nil {
		if resetter, ok := interface{}(rs.Child).(interface{ Reset() }); ok {
			resetter.Reset()
		}
	}
	if resetter, ok := interface{}(&rs.Child2).(interface{ Reset() }); ok {
		resetter.Reset()
	}
}
