// Code generated by generate:reset; DO NOT EDIT.

package audit

func (ae *AuditEvent) Reset() {
	if ae == nil {
		return
	}
	ae.Timestamp = 0
	ae.Action = ""
	ae.UserID = ""
	ae.URL = ""
}

func (fo *FileObserver) Reset() {
	if fo == nil {
		return
	}
	fo.filePath = ""
}

