// Code generated by generate:reset; DO NOT EDIT.

package config

func (c *Config) Reset() {
	if c == nil {
		return
	}
	if resetter, ok := interface{}(&c.Server).(interface{ Reset() }); ok {
		resetter.Reset()
	}
	if resetter, ok := interface{}(&c.Storage).(interface{ Reset() }); ok {
		resetter.Reset()
	}
	if resetter, ok := interface{}(&c.Security).(interface{ Reset() }); ok {
		resetter.Reset()
	}
	if resetter, ok := interface{}(&c.Audit).(interface{ Reset() }); ok {
		resetter.Reset()
	}
	if resetter, ok := interface{}(&c.Profiling).(interface{ Reset() }); ok {
		resetter.Reset()
	}
}
