// Code generated by generate:reset; DO NOT EDIT.

package config

func (c *Config) Reset() {
	if c == nil {
		return
	}
	c.ServerAddr = ""
	c.BaseURL = ""
	c.FileStoragePath = ""
	c.DatabaseDSN = ""
	c.CookieSecret = ""
	c.AuditFilePath = ""
	c.AuditURL = ""
	c.EnablePprof = false
}
